### ISSUE TITLE
Стили применяются глобально

### ISSUE THREAD

**Issue by WiRight** [htmlcssphpjs/codeEditor#1]
Если использовать собственные стили, причем, обратиться к ним глобально (`body`, `html`) то они будут применены на само приложение, а не на содержимое `index.html` с которым ведется работа

![image](https://user-images.githubusercontent.com/26378646/92608669-5612c480-f2be-11ea-9d0b-545612fd6f43.png)

Код для воспроизведения

```html
<!DOCTYPE html>
<html lang="ru">
<head>
<meta charset="UTF-8">
<title>Документ</title>
<style>
body {
  background-color: #f31;  
}  
</style>
</head>
<body>
  <h1>Заголовок</h1>
  <p>Параграф</p>
  <div>hello world</div>
</body>
</html>
```

**Comment by vsecoder-old-account** [comment]
LOL, но я уже не работаю над этим проектом...

**Comment by WiRight** [comment]
Ок_)
